apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: html-loadbalancer
spec:
  replicas: 3
  selector:
    matchLabels:
      name: html-loadbalancer
  template:
    metadata:
      name: html-loadbalancer
      labels:
        name: html-loadbalancer
    spec:
      containers:
        - name: html-loadbalancer
          image: musyahid/htmlcv:1.0
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  type: LoadBalancer
  selector:
    name: html-loadbalancer
  ports:
    - port: 80
      targetPort: 80
