apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cvhtml-nodeport
spec:
  replicas: 3
  selector:
    matchLabels:
      name: html-nodeport
  template:
    metadata:
      name: html-nodeport
      labels:
        name: html-nodeport
    spec:
      containers:
        - name : html-nodeport
          image: musyahid/htmlcv:1.0
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: html-service-nodeport
spec:
  type: NodePort
  selector: 
    name: html-nodeport
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
